### ISSUE TITLE
Import error [VS2012 vs Python27?]

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CGAL/cgal-swig-bindings#39]
```
Hello to everybody, I'm trying to make a precompiled installer for the CGAL 
bindings for Python 2.7 for win32 and I have some problem in importing the 
modules.

What I did.
-----------
I did the following macro-steps:
1) I compiled CGAL-4.3 using Visual Studio - win32;
2) I compiled CGAL-bindings using Visual Studio - win32;
Then I've put the resulting files in a single folder "CGAL" (by joining the 
folders "build-python\CGAL" and "build-python\CGAL\Release". Here is a summary 
of the files I can found directly under my "CGAL" folder:
- "__init__.py"
- "CGAL_[module].py"
- "_CGAL_[module].exp"
- "_CGAL_[module].lib"
- "_CGAL_[module].pyd"
( for every [module] in the bindings )

The problem.
------------
I'm trying to load a module, to see if everything is working properly. For 
example, let's take "CGAL_Kernel". I open a Python console inside the "CGAL" 
folder and here is my error:

    >>> import sys
    >>> sys.path.append(CGAL_folder)
    >>> import CGAL_Kernel
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "CGAL_Kernel.py", line 28, in <module>
        _CGAL_Kernel = swig_import_helper()
      File "CGAL_Kernel.py", line 24, in swig_import_helper
        _mod = imp.load_module('_CGAL_Kernel', fp, pathname, description)
    ImportError: DLL load failed

Of course I get the same error if I try "import _CGAL_Kernel.pyd".

System informations:
--------------------
I'm using Windows 7 x64, Python 2.7 win32. The CGAL were compiled using Visual 
Studio 2012 Professional, in "Release" mode, for win32 systems (and the python 
bindings too).

I wonder what I'm doing wrong, maybe I have to compile everything using Visual 
Studio 2008 (or compiling Python with VS2012)?

Best regards, and thank you for your work!

P.S. If I manage to make it work I can make a "setup.py" and upload some 
precompiled-binary-installer.

```

Original issue reported on code.google.com by `marco.ce...@gmail.com` on 8 Nov 2013 at 1:55

**Comment by NikWillmore** [comment]
Conclusion after tinkering with CGAL-SWIG on Windows 10 64 bit with a working installation of C++ CGAL, latest Visual Studio and latest everything, including optional packages, is that the CGAL-SWIG Python system is broken and just doesn't work when installed on Windows per instructions. I isolated/extracted the issue into two lines of mere Python import code used by the SWIG packages that should work out of the box but fail with very little information. Dependency Walker indeed points to all sorts of Windows DLLs being not found (in the SWIG directory, no less). This isn't geometry programming, it's low level Windows dysfunction likely caused by CGAL/SWIG developers only testing things on Linux, explaining why there are no longer any simple installers for Windows even for CGAL.

![cgal_swig](https://user-images.githubusercontent.com/11458028/30949777-85185904-a3e6-11e7-849d-b2103470e054.PNG)

**Comment by sloriot** [comment]
I don't have any windows machine so I'm not able to test it. Naively I would say that python does not see the library file so it might just be a matter of setting a path correctly. Is `PYTHONPATH` containing the path of the lib?

**Comment by lrineau** [comment]
Maxime @maxGimeno and I have confirmed that there is an issue with cgal-swig-bindings on Windows. The issue is related to `__declspec(dllexport)`. We have already fixed part of the problem, with the commit https://github.com/CGAL/cgal-swig-bindings/commit/b55e0b836f8e16a97321b293cfa3394aeb4260e9, but now we have warnings saying that, for example, the `Point_2` class of the bindings requires that `CGAL::Point_2<Epick>` is exported as well. That seems to require: 
- support from `CGAL::Point_2` (with a macro), and
- an explicit instanciation.
And that for all objects of the kernel.

**Comment by lrineau** [comment]
Actually, maybe it is simpler: maybe `CGAL_Kernel_cpp.dll` was not in the `PATH`, and thus `_Kernel.pyd` was not able to initialize correctly.
