### ISSUE TITLE
No module named _CGAL_Point_set_processing_3

### ISSUE THREAD

**Issue by jpiabrantes** [CGAL/cgal-swig-bindings#75]
I just installed CGAL on ubuntu doing `sudo apt-get install libcgal-dev` then I installed the python bindings doing `pip install cgal-bindings` (I also tried to install using the source and the results were similar). I then start running the examples on cgal-swig-bindings/examples/python folder and whenever I need to import the `CGAL_Point_set_processing_3` module it fails:

```python
Traceback (most recent call last):
  File "Point_set_processing_3_test.py", line 4, in <module>
    from CGAL.CGAL_Point_set_processing_3 import *
  File "/home/joao/anaconda2/lib/python2.7/site-packages/CGAL/CGAL_Point_set_processing_3.py", line 28, in <module>
    _CGAL_Point_set_processing_3 = swig_import_helper()
  File "/home/joao/anaconda2/lib/python2.7/site-packages/CGAL/CGAL_Point_set_processing_3.py", line 20, in swig_import_helper
    import _CGAL_Point_set_processing_3
ImportError: No module named _CGAL_Point_set_processing_3
```

On my `anaconda2/lib/python2.7/site-packages/CGAL/` folder I have the `CGAL_Point_set_processing_3.py` file but I don't have the `_CGAL_Point_set_processing_3.so` file. What can I do?

**Comment by lrineau** [comment]
I'll try to reproduce the issue. Which Ubuntu version? 16?

**Comment by jpiabrantes** [comment]
@lrineau yes, Ubuntu 16.04

**Comment by jpiabrantes** [comment]
@lrineau any news on this?

**Comment by lrineau** [comment]
I have tried and cannot reproduce your issues.

Anyway, the pypi setup of cgal-bindings is not made by us, but by @sciencectn. See https://pypi.python.org/pypi/cgal-bindings/0.0.7

In theh `setup.py`, I see
>   "Point_set_processing_3",       # needs eigen3

Do you have Eigen3 installed?
